Music_App/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :show, :destroy, :update, :edit]
end

Music_App/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band_id, :live, presence: true
  validates :live, inclusion: {in: [true, false] }
  after_initialize :translate_live_string


  def translate_live_string
      self.live ||= false
  end
end

Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music_App/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

end

Music_App/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

end

Music_App/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    render :new
  end

  def create
    album = Album.new(album_params)
    if album.save!
      redirect_to album_url(album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def show
    render :show
  end

  def update
    album = Album.find_by(id: params[:id])
    if album.update
      redirect_to album_url(album)
    else
      flash.now[:errors] = album.errors.full_messages
      render :edit
    end
  end

  def destroy
    album = Album.find_by(id: params[:id])
    album.destroy
    redirect_to bands_url
  end


  private

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end
end

Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  helper_method :current_band
  helper_method :current_album


  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_band
    @current_band = Band.find_by(id: params[:id])
  end

  def current_album
    @current_album ||= Album.find_by(id: params[:id])
  end
end

Music_App/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def new
    @band = Band.new
    render :new
  end

  def index
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    band = Band.find_by(id: params[:id])
    if band
      render :show
    else
      redirect_to bands_url
    end
  end

  def destroy
    band = Band.find_by(id: params[:id])
    band.destroy
    redirect_to bands_url
  end

  def update
    band = Band.find_by(id: params[:id])
    if band.update(band_params)
      redirect_to band_url(band)
    else
      flash.now[:errors] = band.errors.full_messages
      render :edit
    end
  end

  def edit
    render :edit
  end


  private

  def band_params
    params.require(:band).permit(:name)
  end

end

Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password])
    if user
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Wrong password or email"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :email)
  end

end

Music_App/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html =  "<input
            type='hidden'
            name='authenticity_token'
            value='#{form_authenticity_token}'
            />"

    html.html_safe
  end
end

Music_App/app/views/albums/edit.html.erb
<h1>Edit this album</h1>

<% if flash.now[:errors] %>
<ul>
  <% flash.now[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>
<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  </form>
  <%= auth_token %>
  <label>Title:
    <input type="text" name="album[title]" value=" <%= current_album.title %>">
  </label>

  <br><br>

  <label>Year:
    <input type="number" name="album[year]" value= "<%= current_album.year %>">
  </label>

  <br><br>
  <label>Choose Band
    <select name="album[band_id]">
      <option disabled value="">--Please choose a band--</option>
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= band.id == current_album.band_id ? "selected" : "" %> ><%= band.name %></option>
      <% end %>
    </select>
  </label>

  <br><br>

  <input type="radio" name="album[live]" value="true" <%= current_album.live == true ? "checked" : "" %> >Live <br>
  <input type="radio" name="album[live]" value="false" <%= current_album.live == false ? "checked" : "" %>>Studio <br>

  <br><br>

  <input type="submit" value="Finish">

</form>

Music_App/app/views/albums/new.html.erb
<h1>Add an album</h1>


<% if flash.now[:errors] %>
<ul>
  <% flash.now[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>


<form action="<%= albums_url %>" method="post">
  <%= auth_token %>

  <label>Title:
    <input type="text" name="album[title]">
  </label>

  <br><br>

  <label>Year:
    <input type="number" name="album[year]">
  </label>

  <br><br>

  <label>Choose Band
    <select name="album[band_id]">
      <option disabled value="">--Please choose a band--</option>
      <% Band.all.each do |band| %>
        <option value="<%= band.id %>" <%= params[:band_id] == band.id ? "selected" : "" %> ><%= band.name %></option>
      <% end %>
    </select>
  </label>

  <br><br>

  <input type="radio" name="album[live]" value="true">Live <br>
  <input type="radio" name="album[live]" value="false">Studio <br>

  <br><br>

  <input type="submit" value="Finish">

</form>

Music_App/app/views/albums/show.html.erb
<h2><%= current_album.title %></h2>


<h1>Year: <%= current_album.year %> </h1>
<h1>Band: <%= Band.find_by(id: current_album.band_id).name %> </h1>
<% if current_album.live == true %>
<h1>Live Album</h1>
<% else %>
<h1>Studio Album</h1>
<% end %>
<a href=" <%= edit_album_url(current_album) %> ">Edit this album</a><br><br>
<a href=" <%= bands_url %> ">Back to bands</a>

Music_App/app/views/bands/edit.html.erb
<h1>Edit <%= current_band.name %></h1>

<form action="<%= band_url(current_band) %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="patch">

  <label>Band name:
    <input type="text" name="band[name]" value=" <%= current_band.name %>">
  </label>

  <br><br>

  <input type="submit" value="Add">

</form>

Music_App/app/views/bands/index.html.erb
<h1>All The Bands!</h1>

<ul>
  <% Band.all.each do |band| %>
    <li>
      <a href="<%= band_url(band) %>"><%= band.name %></a>
    </li>
  <% end %>
</ul>

Music_App/app/views/bands/new.html.erb
<h1>Add a Band</h1>

<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label>Band name:
    <input type="text" name="band[name]">
  </label>

  <br><br>

  <input type="submit" value="Add">

</form>

Music_App/app/views/bands/show.html.erb
<h1><%= current_band.name %></h1>
<br>

<a href="<%= edit_band_url(current_band) %>">Edit this Band</a>
<br>
<form action=" <%= band_url(current_band) %> " method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">

  <input type="submit" value="Delete Band">
</form>
<br><br><br>
<a href=" <%= new_band_album_url(current_band) %>">Add an album</a><br><br>
<a href=" <%= bands_url %>">Back to Bands</a>

Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Music App</h1>

      <% if current_user %>
      <form  action=" <%= session_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Log Out">
      </form>
      <% else %>
      <a href="<%= new_session_url %>">Sign In!</a>
      <a href="<%= new_user_url %>">Create Account!</a>
      <% end %>
    </header>

    <br><br>

    <%= yield %>

  </body>
</html>

Music_App/app/views/users/new.html.erb
<h1>Create account!</h1>

<% if flash.now[:errors] %>
<ul>
  <% flash.now[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>
<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label>Email:
    <input type="text" name="user[email]">
  </label>

  <br><br>

  <label>Password:
    <input type="password" name="user[password]">
  </label>

  <br><br>

  <input type="submit" value="Submit">
</form>

Music_App/app/views/users/show.html.erb
<h1>Hello, <%= current_user.email %>!</h1>